import joblib
import numpy as np
import pandas as pd

# Load model, scaler, and label encoder

# import os
# print(f"this is from crop recom:{os.getcwd()}")


#/Users/sagarpoudel/Desktop/FuseMachines/project/crop-prediction/crop-prediction/final/server/crop/server/crop/labelencoderxgb.pkl
model = joblib.load('crop/modelxgb.pkl')
sc = joblib.load('crop/scalerxgb.pkl')
le = joblib.load('crop/labelencoderxgb.pkl')



crop_info= {
        "rice":"धान खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: धानको खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। धानको लागि बलियो माटो, जुन पानीको सही व्यवस्थापन गर्न सक्छ, आवश्यक छ। तपाईंले माटोको PH स्तर ५.५-७ रहेको भूमिमा धान लगाउने योजना बनाउनुपर्छ। पहिलो, माटोलाई राम्रोसँग जुत्नुपर्छ र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। धानको बीउ लगाउने क्रममा २०-२५ किलोग्राम प्रति हेक्टरको दरमा बीउको चयन गर्नुहोस्। बिउ लगाएको १०-१५ दिनपछि, जिउँदो बोटहरूलाई जङ्गल र अन्य खरिपातबाट जोगाउन नियमित रुपमा खरिपात हटाउन महत्त्वपूर्ण छ। पानीको व्यवस्थापनमा ध्यान दिनुहोस्; धानको बोटको वृद्धि सुनिश्चित गर्न पर्याप्त पानीको आवश्यकता हुन्छ। बोटको वृद्धि र बालीको सुरक्षा सुनिश्चित गर्न सही समयमा खतरा नियन्त्रण गर्न नबिर्सनुहोस्। अन्तमा, धानको बाली काढ्नका लागि सही समयको लागि सतर्क रहनुहोस्।",
        "maize":"मकै खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: मकै खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। मकैको लागि गहिरो, उपजाऊ, र राम्रो जल निकासी भएको माटो उपयुक्त मानिन्छ। माटोको PH स्तर ५.८-७.० रहेको भए राम्रो हुन्छ। पहिलो, माटोलाई राम्रोसँग जुत्नुपर्छ र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। मकैको बीउ लगाउने क्रममा २५-३० किलोग्राम प्रति हेक्टरको दरमा बीउको चयन गर्नुहोस्। बिउ लगाएको ७-१० दिनपछि, जिउँदो बोटहरूलाई जङ्गल र अन्य खरिपातबाट जोगाउन नियमित रुपमा खरिपात हटाउन महत्त्वपूर्ण छ। पानीको व्यवस्थापनमा ध्यान दिनुहोस्; मकैको बोटको वृद्धि र विकासका लागि २५-३० दिनको अन्तरालमा पर्याप्त पानीको आवश्यकता हुन्छ। बोटको वृद्धि र बालीको सुरक्षा सुनिश्चित गर्न सही समयमा खतरा नियन्त्रण गर्न नबिर्सनुहोस्। अन्तमा, मकैको बाली काढ्नका लागि सही समयको लागि सतर्क रहनुहोस्।",
        "chickpea":"चना खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: चना खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। चनाको लागि बलियो, उपजाऊ, र राम्रो जल निकासी भएको माटो आवश्यक छ, र माटोको PH स्तर ६.०-७.५ हुनु उपयुक्त मानिन्छ। पहिलो, माटोलाई राम्रोसँग जुत्नुपर्छ र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। चनाको बीउ लगाउने क्रममा ५०-६० किलोग्राम प्रति हेक्टरको दरमा बीउको चयन गर्नुहोस्। बिउ लगाएको ५-७ दिनपछि, जिउँदो बोटहरूलाई जङ्गल र अन्य खरिपातबाट जोगाउन नियमित रुपमा खरिपात हटाउन महत्त्वपूर्ण छ। चनाको बोटलाई आवश्यक पानीको मात्रा उपलब्ध गराउनुहोस्, विशेष गरी फूल र फलको विकासको समयमा। बोटको वृद्धि र बालीको सुरक्षा सुनिश्चित गर्न सही समयमा खतरा नियन्त्रण गर्न नबिर्सनुहोस्। अन्तमा, चनाको बाली काढ्नका लागि सही समयको लागि सतर्क रहनुहोस्।",
        "kidneybeans":"राजमा खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: राजमा खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। राजमाको लागि बलियो, उपजाऊ, र राम्रो जल निकासी भएको माटो आवश्यक छ, र माटोको PH स्तर ६.०-७.० हुनु उपयुक्त मानिन्छ। पहिलो, माटोलाई राम्रोसँग जुत्नुपर्छ र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। राजमाको बीउ लगाउने क्रममा ३०-४० किलोग्राम प्रति हेक्टरको दरमा बीउको चयन गर्नुहोस्। बिउ लगाएको ७-१० दिनपछि, जिउँदो बोटहरूलाई जङ्गल र अन्य खरिपातबाट जोगाउन नियमित रुपमा खरिपात हटाउन महत्त्वपूर्ण छ। राजमाको बोटलाई पर्याप्त पानी उपलब्ध गराउनुहोस्, विशेष गरी फूल र फलको विकासको समयमा। बोटको वृद्धि र बालीको सुरक्षा सुनिश्चित गर्न सही समयमा खतरा नियन्त्रण गर्न नबिर्सनुहोस्। अन्तमा, राजमाको बाली काढ्नका लागि सही समयको लागि सतर्क रहनुहोस्।",
        "pigeonpeas":"रहर (पिजोन पी) खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: रहर खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। रहरको लागि उपजाऊ र राम्रो जल निकासी भएको माटो आवश्यक छ, र माटोको pH स्तर ६.०-७.५ हुनु उपयुक्त मानिन्छ। पहिलो, माटोलाई राम्रोसँग जुत्नुपर्छ र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। रहरको बीउ १५-२० किलोग्राम प्रति हेक्टरको दरमा चयन गर्नुहोस्। बिउ लगाएको १०-१५ दिनपछि, बोटलाई जङ्गल र खरिपातबाट जोगाउन नियमित रुपमा खरिपात हटाउनु महत्त्वपूर्ण छ। रहरको बोटलाई फूल र फलको विकासको समयमा पर्याप्त पानी उपलब्ध गराउनुहोस्। बोटको वृद्धि र बालीको सुरक्षा सुनिश्चित गर्न सही समयमा कीट नियन्त्रण गर्न नबिर्सनुहोस्। अन्तमा, रहरको बाली सही समयमा काट्नका लागि सतर्क रहनुहोस्।",
        "mothbeans":"सिमी खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: सिमी खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। सिमीको लागि हल्का, उपजाऊ, र राम्रो जल निकासी भएको माटो आवश्यक छ, र माटोको PH स्तर ६.०-७.० हुनु उपयुक्त मानिन्छ। पहिलो, माटोलाई राम्रोसँग जुत्नुपर्छ र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। सिमीको बीउ लगाउने क्रममा १५-२० किलोग्राम प्रति हेक्टरको दरमा बीउको चयन गर्नुहोस्। बिउ लगाएको ७-१० दिनपछि, जिउँदो बोटहरूलाई जङ्गल र अन्य खरिपातबाट जोगाउन नियमित रुपमा खरिपात हटाउन महत्त्वपूर्ण छ। सिमीको बोटलाई पर्याप्त पानी उपलब्ध गराउनुहोस्, विशेष गरी फूल र फलको विकासको समयमा। बोटको वृद्धि र बालीको सुरक्षा सुनिश्चित गर्न सही समयमा खतरा नियन्त्रण गर्न नबिर्सनुहोस्। अन्तमा, सिमीको बाली काढ्नका लागि सही समयको लागि सतर्क रहनुहोस्।",
        "mungbean":"मुगं (मुग) खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: मुगं खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। मुगंको लागि हल्का, उपजाऊ, र राम्रो जल निकासी भएको माटो आवश्यक छ, र माटोको PH स्तर ६.०-७.० हुनु उपयुक्त मानिन्छ। पहिलो, माटोलाई राम्रोसँग जुत्नुपर्छ र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। मुगंको बीउ लगाउने क्रममा १५-२० किलोग्राम प्रति हेक्टरको दरमा बीउको चयन गर्नुहोस्। बिउ लगाएको ७-१० दिनपछि, जिउँदो बोटहरूलाई जङ्गल र अन्य खरिपातबाट जोगाउन नियमित रुपमा खरिपात हटाउन महत्त्वपूर्ण छ। मुगंको बोटलाई पर्याप्त पानी उपलब्ध गराउनुहोस्, विशेष गरी फूल र फलको विकासको समयमा। बोटको वृद्धि र बालीको सुरक्षा सुनिश्चित गर्न सही समयमा खतरा नियन्त्रण गर्न नबिर्सनुहोस्। अन्तमा, मुगंको बाली काढ्नका लागि सही समयको लागि सतर्क रहनुहोस्।",
        "blackgram":"मास (काले चना) खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: मास खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। मासको लागि हल्का, उपजाऊ, र राम्रो जल निकासी भएको माटो आवश्यक छ, र माटोको PH स्तर ६.०-७.० हुनु उपयुक्त मानिन्छ। पहिलो, माटोलाई राम्रोसँग जुत्नुपर्छ र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। मासको बीउ लगाउने क्रममा २०-२५ किलोग्राम प्रति हेक्टरको दरमा बीउको चयन गर्नुहोस्। बिउ लगाएको ७-१० दिनपछि, जिउँदो बोटहरूलाई जङ्गल र अन्य खरिपातबाट जोगाउन नियमित रुपमा खरिपात हटाउन महत्त्वपूर्ण छ। मासको बोटलाई पर्याप्त पानी उपलब्ध गराउनुहोस्, विशेष गरी फूल र फलको विकासको समयमा। बोटको वृद्धि र बालीको सुरक्षा सुनिश्चित गर्न सही समयमा खतरा नियन्त्रण गर्न नबिर्सनुहोस्। अन्तमा, मासको बाली काढ्नका लागि सही समयको लागि सतर्क रहनुहोस्।",
        "lentil":"मासुर (लेन्टिल) खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: मासुर खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। मासुरको लागि हल्का, उपजाऊ, र राम्रो जल निकासी भएको माटो आवश्यक छ, र माटोको PH स्तर ६.०-७.५ हुनु उपयुक्त मानिन्छ। पहिलो, माटोलाई राम्रोसँग जुत्नुपर्छ र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। मासुरको बीउ लगाउने क्रममा २५-३० किलोग्राम प्रति हेक्टरको दरमा बीउको चयन गर्नुहोस्। बिउ लगाएको ७-१० दिनपछि, जिउँदो बोटहरूलाई जङ्गल र अन्य खरिपातबाट जोगाउन नियमित रुपमा खरिपात हटाउन महत्त्वपूर्ण छ। मासुरको बोटलाई पर्याप्त पानी उपलब्ध गराउनुहोस्, विशेष गरी फूल र फलको विकासको समयमा। बोटको वृद्धि र बालीको सुरक्षा सुनिश्चित गर्न सही समयमा खतरा नियन्त्रण गर्न नबिर्सनुहोस्। अन्तमा, मासुरको बाली काढ्नका लागि सही समयको लागि सतर्क रहनुहोस्।",
        "pomegranate":"अनार खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: अनार खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। अनारको लागि हल्का, उपजाऊ, र राम्रो जल निकासी भएको माटो आवश्यक छ, र माटोको PH स्तर ५.५-७.० हुनु उपयुक्त मानिन्छ। पहिलो, अनारको बिरुवा लगाउनु अघि माटोलाई राम्रोसँग तयारी गर्नुहोस् र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। अनारको बिरुवा १-२ मीटरको दूरीमा रोप्नुहोस्, र बिरुवालाई उचित पानीको मात्रा उपलब्ध गराउनुहोस्, विशेष गरी गर्मीको मौसममा। अनारको बिरुवालाई नियमित रुपमा खरिपात हटाउन महत्त्वपूर्ण छ र बोटको वृद्धि र स्वास्थ्यको लागि उचित ढंगले मल र पानीको व्यवस्था गर्नुहोस्। फूल र फलको विकासको समयमा ध्यान दिनुहोस्, र आवश्यक पर्दा किटनाशकको प्रयोग गर्नुहोस्। अन्तमा, अनारको बाली काढ्नका लागि सही समयको लागि सतर्क रहनुहोस् र बालीलाई उचित तरिकाले भण्डारण गर्नुहोस्।",
        "banana":"केरा खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: केरा खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। केराको लागि समशीतोष्ण र गर्म जलवायु उपयुक्त हुन्छ, र माटोको PH स्तर ५.५-७.० हुनु उपयुक्त मानिन्छ। पहिलो, माटोलाई राम्रोसँग जुत्नुपर्छ र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। केरा रोप्ने बेला, प्रत्येक बिरुवालाई २-३ मिटरको दूरीमा रोप्नुहोस्। केरा बिरुवालाई पर्याप्त पानी उपलब्ध गराउनुहोस्, विशेष गरी गर्मीको मौसममा, र जङ्गल र खरिपातबाट जोगाउन नियमित रूपमा खरिपात हटाउन महत्त्वपूर्ण छ। फूल र फलको विकासको समयमा विशेष ध्यान दिनुहोस् र आवश्यक पर्दा किटनाशकको प्रयोग गर्नुहोस्। अन्तमा, केराको बाली काढ्नका लागि सही समयको लागि सतर्क रहनुहोस् र बालीलाई उचित तरिकाले भण्डारण गर्नुहोस्।",
        "mango":"आप (आम) खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: आप खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। आपको लागि गर्म र समशीतोष्ण जलवायु उपयुक्त हुन्छ, र माटोको PH स्तर ६.०-७.५ हुनु उपयुक्त मानिन्छ। पहिलो, माटोलाई राम्रोसँग जुत्नुपर्छ र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। आपको बिरुवा रोप्ने बेला, प्रत्येक बिरुवालाई ८-१० मिटरको दूरीमा रोप्नुहोस्। आपको बिरुवालाई पर्याप्त पानी उपलब्ध गराउनुहोस्, विशेष गरी गर्मीको मौसममा, र बिरुवालाई नियमित रूपमा खरिपात र जङ्गलबाट जोगाउन महत्त्वपूर्ण छ। आपको फूल र फलको विकासको समयमा ध्यान दिनुहोस् र आवश्यक पर्दा किटनाशकको प्रयोग गर्नुहोस्। अन्तमा, आपको बाली काढ्नका लागि सही समयको लागि सतर्क रहनुहोस् र बालीलाई उचित तरिकाले भण्डारण गर्नुहोस्।",
        "grapes":"अंगुर खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: अंगुर खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। अंगुरको लागि गर्म, सुखा र राम्रो जल निकासी भएको माटो आवश्यक छ, र माटोको PH स्तर ६.०-६.५ हुनु उपयुक्त मानिन्छ। पहिलो, माटोलाई राम्रोसँग तयारी गर्नुहोस् र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। अंगुरको बिरुवा रोप्ने बेला, प्रत्येक बिरुवालाई २-३ मीटरको दूरीमा रोप्नुहोस्। अंगुरको बिरुवालाई पर्याप्त पानी उपलब्ध गराउनुहोस्, विशेष गरी फूल र फलको विकासको समयमा। नियमित रूपमा खरिपात हटाउन महत्त्वपूर्ण छ र बिरुवाको वृद्धि र स्वास्थ्यको लागि उचित मल र पानीको व्यवस्था गर्नुहोस्। फूल र फलको विकासको समयमा ध्यान दिनुहोस्, र आवश्यक पर्दा किटनाशकको प्रयोग गर्नुहोस्। अन्तमा, अंगुरको बाली काढ्नका लागि सही समयको लागि सतर्क रहनुहोस् र बालीलाई उचित तरिकाले भण्डारण गर्नुहोस्।",
        "watermelon":"खरबुजा खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: खरबुजा खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। खरबुजाको लागि गर्म र सुखा जलवायु उपयुक्त हुन्छ, र माटोको PH स्तर ६.०-६.८ हुनु उपयुक्त मानिन्छ। पहिलो, माटोलाई राम्रोसँग जुत्नुपर्छ र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। खरबुजाको बीउ रोप्ने बेला, १-२ मीटरको दूरीमा रोप्नुहोस्। खरबुजाको बिरुवालाई पर्याप्त पानी उपलब्ध गराउनुहोस्, विशेष गरी फूल र फलको विकासको समयमा। नियमित रूपमा खरिपात हटाउन महत्त्वपूर्ण छ र बिरुवाको वृद्धि र स्वास्थ्यको लागि उचित मल र पानीको व्यवस्था गर्नुहोस्। फूल र फलको विकासको समयमा ध्यान दिनुहोस्, र आवश्यक पर्दा किटनाशकको प्रयोग गर्नुहोस्। अन्तमा, खरबुजाको बाली काढ्नका लागि सही समयको लागि सतर्क रहनुहोस् र बालीलाई उचित तरिकाले भण्डारण गर्नुहोस्।",
        "muskmelon":"मास्क मेलोन खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: मास्क मेलोन खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। मास्क मेलोनको लागि गर्म र सुखा जलवायु उपयुक्त हुन्छ, र माटोको PH स्तर ६.०-६.८ हुनु उपयुक्त मानिन्छ। पहिलो, माटोलाई राम्रोसँग जुत्नुपर्छ र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। मास्क मेलोनको बीउ रोप्ने बेला, १-२ मीटरको दूरीमा रोप्नुहोस्। मास्क मेलोनको बिरुवालाई पर्याप्त पानी उपलब्ध गराउनुहोस्, विशेष गरी फूल र फलको विकासको समयमा। नियमित रूपमा खरिपात हटाउन महत्त्वपूर्ण छ र बिरुवाको वृद्धि र स्वास्थ्यको लागि उचित मल र पानीको व्यवस्था गर्नुहोस्। फूल र फलको विकासको समयमा ध्यान दिनुहोस्, र आवश्यक पर्दा किटनाशकको प्रयोग गर्नुहोस्। अन्तमा, मास्क मेलोनको बाली काढ्नका लागि सही समयको लागि सतर्क रहनुहोस् र बालीलाई उचित तरिकाले भण्डारण गर्नुहोस्।",
        "apple":"स्याउ खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: स्याउ खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। स्याउको लागि चिसो र समशीतोष्ण जलवायु उपयुक्त हुन्छ, र माटोको PH स्तर ६.०-७.० हुनु उपयुक्त मानिन्छ। पहिलो, माटोलाई राम्रोसँग जुत्नुपर्छ र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। स्याउको बिरुवा रोप्ने बेला, प्रत्येक बिरुवालाई ५-७ मीटरको दूरीमा रोप्नुहोस्। स्याउको बिरुवालाई पर्याप्त पानी उपलब्ध गराउनुहोस्, विशेष गरी फूल र फलको विकासको समयमा। नियमित रूपमा खरिपात हटाउन महत्त्वपूर्ण छ र बिरुवाको वृद्धि र स्वास्थ्यको लागि उचित मल र पानीको व्यवस्था गर्नुहोस्। फूल र फलको विकासको समयमा ध्यान दिनुहोस्, र आवश्यक पर्दा किटनाशकको प्रयोग गर्नुहोस्। अन्तमा, स्याउको बाली काढ्नका लागि सही समयको लागि सतर्क रहनुहोस् र बालीलाई उचित तरिकाले भण्डारण गर्नुहोस्।",
        "orange":"सुन्तला खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: सुन्तला खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। सुन्तलाको लागि गर्म र समशीतोष्ण जलवायु उपयुक्त हुन्छ, र माटोको PH स्तर ६.०-७.५ हुनु उपयुक्त मानिन्छ। पहिलो, माटोलाई राम्रोसँग जुत्नुपर्छ र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। सुन्तला बिरुवा रोप्ने बेला, प्रत्येक बिरुवालाई ६-८ मीटरको दूरीमा रोप्नुहोस्। सुन्तला बिरुवालाई पर्याप्त पानी उपलब्ध गराउनुहोस्, विशेष गरी फूल र फलको विकासको समयमा। नियमित रूपमा खरिपात हटाउन महत्त्वपूर्ण छ र बिरुवाको वृद्धि र स्वास्थ्यको लागि उचित मल र पानीको व्यवस्था गर्नुहोस्। फूल र फलको विकासको समयमा ध्यान दिनुहोस्, र आवश्यक पर्दा किटनाशकको प्रयोग गर्नुहोस्। अन्तमा, सुन्तला बाली काढ्नका लागि सही समयको लागि सतर्क रहनुहोस् र बालीलाई उचित तरिकाले भण्डारण गर्नुहोस्।",
        "papaya":"मेवा खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: मेवा खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। मेवाका लागि गर्म र आर्द्र जलवायु उपयुक्त हुन्छ, र माटोको PH स्तर ६.०-७.० हुनु उपयुक्त मानिन्छ। पहिलो, माटोलाई राम्रोसँग जुत्नुपर्छ र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। मेवाको बिरुवा रोप्ने बेला, प्रत्येक बिरुवालाई २-३ मीटरको दूरीमा रोप्नुहोस्। मेवाको बिरुवालाई पर्याप्त पानी उपलब्ध गराउनुहोस्, विशेष गरी गर्मीको समयमा। नियमित रूपमा खरिपात हटाउन महत्त्वपूर्ण छ र बिरुवाको वृद्धि र स्वास्थ्यको लागि उचित मल र पानीको व्यवस्था गर्नुहोस्। फूल र फलको विकासको समयमा ध्यान दिनुहोस्, र आवश्यक पर्दा किटनाशकको प्रयोग गर्नुहोस्। अन्तमा, मेवाको बाली काढ्नका लागि सही समयको लागि सतर्क रहनुहोस् र बालीलाई उचित तरिकाले भण्डारण गर्नुहोस्।",
        "coconut":"नारियल खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: नारियल खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। नारियलको लागि गर्म, आर्द्र जलवायु उपयुक्त हुन्छ, र माटोको PH स्तर ५.०-८.० बीच हुनु उपयुक्त मानिन्छ। पहिलो, माटोलाई राम्रोसँग तयारी गर्नुहोस् र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। नारियलको बिरुवा रोप्ने बेला, प्रत्येक बिरुवालाई ७-८ मीटरको दूरीमा रोप्नुहोस्। नारियलको बिरुवालाई पर्याप्त पानी उपलब्ध गराउनुहोस्, विशेष गरी गर्मीको समयमा। नियमित रूपमा खरिपात हटाउन महत्त्वपूर्ण छ र बिरुवाको वृद्धि र स्वास्थ्यको लागि उचित मल र पानीको व्यवस्था गर्नुहोस्। फूल र फलको विकासको समयमा ध्यान दिनुहोस्, र आवश्यक पर्दा किटनाशकको प्रयोग गर्नुहोस्। अन्तमा, नारियलको बाली काढ्नका लागि सही समयको लागि सतर्क रहनुहोस् र बालीलाई उचित तरिकाले भण्डारण गर्नुहोस्।",
        "cotton":"सूती खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: सूती खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। सूतीको लागि गर्म र सुखा जलवायु उपयुक्त हुन्छ, र माटोको PH स्तर ६.०-७.५ हुनु उपयुक्त मानिन्छ। पहिलो, माटोलाई राम्रोसँग जुत्नुपर्छ र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। सूतीको बीउ रोप्ने बेला, प्रत्येक बीउलाई २०-२५ सेन्टिमिटरको दूरीमा रोप्नुहोस्। सूती बिरुवालाई पर्याप्त पानी उपलब्ध गराउनुहोस्, विशेष गरी फूल र फलको विकासको समयमा। नियमित रूपमा खरिपात हटाउन महत्त्वपूर्ण छ र बिरुवाको वृद्धि र स्वास्थ्यको लागि उचित मल र पानीको व्यवस्था गर्नुहोस्। फूल र फलको विकासको समयमा ध्यान दिनुहोस्, र आवश्यक पर्दा किटनाशकको प्रयोग गर्नुहोस्। अन्तमा, सूतीको बाली काढ्नका लागि सही समयको लागि सतर्क रहनुहोस् र बालीलाई उचित तरिकाले भण्डारण गर्नुहोस्।",
        "jute":"जुट खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: जुट खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। जुटको लागि गर्म, आर्द्र जलवायु उपयुक्त हुन्छ, र माटोको PH स्तर ६.०-७.५ हुनु उपयुक्त मानिन्छ। पहिलो, माटोलाई राम्रोसँग जुत्नुपर्छ र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। जुटको बीउ रोप्ने बेला, प्रत्येक बीउलाई २५-३० सेन्टिमिटरको दूरीमा रोप्नुहोस्। जुटको बिरुवालाई पर्याप्त पानी उपलब्ध गराउनुहोस्, विशेष गरी फूल र फलको विकासको समयमा। नियमित रूपमा खरिपात हटाउन महत्त्वपूर्ण छ र बिरुवाको वृद्धि र स्वास्थ्यको लागि उचित मल र पानीको व्यवस्था गर्नुहोस्। फूल र फलको विकासको समयमा ध्यान दिनुहोस्, र आवश्यक पर्दा किटनाशकको प्रयोग गर्नुहोस्। अन्तमा, जुटको बाली काढ्नका लागि सही समयको लागि सतर्क रहनुहोस् र बालीलाई उचित तरिकाले भण्डारण गर्नुहोस्।",
        "coffee":"कफी खेती गर्न चाहने किसानका लागि पूर्ण मार्गनिर्देश: कफी खेतीका लागि उपयुक्त जलवायु र माटोको चयन महत्त्वपूर्ण छ। कफीको लागि समशीतोष्ण र आर्द्र जलवायु उपयुक्त हुन्छ, जहाँ तापक्रम १५-२४ डिग्री सेल्सियस हुनुपर्छ। माटोको PH स्तर ६.०-६.५ हुनु उपयुक्त मानिन्छ। पहिलो, माटोलाई राम्रोसँग जुत्नुपर्छ र आवश्यक पोषक तत्वहरू जस्तै नाइट्रोजन, फस्फोरस, र पोटासियमको प्रयोग गर्नुपर्छ। कफीको बिरुवा रोप्ने बेला, प्रत्येक बिरुवालाई १-२ मीटरको दूरीमा रोप्नुहोस्। कफीको बिरुवालाई पर्याप्त पानी उपलब्ध गराउनुहोस्, विशेष गरी गर्मीको समयमा। नियमित रूपमा खरिपात हटाउन महत्त्वपूर्ण छ र बिरुवाको वृद्धि र स्वास्थ्यको लागि उचित मल र पानीको व्यवस्था गर्नुहोस्। फूल र फलको विकासको समयमा ध्यान दिनुहोस्, र आवश्यक पर्दा किटनाशकको प्रयोग गर्नुहोस्। अन्तमा, कफीको बाली काढ्नका लागि सही समयको लागि सतर्क रहनुहोस् र बालीलाई उचित तरिकाले भण्डारण गर्नुहोस्।"
    }
crop_info_en = {
    "rice": "Complete guide for farmers wanting to grow rice: Choosing the right climate and soil is crucial for rice cultivation. Strong soil that can manage water properly is necessary for rice. You should plan to plant rice in soil with a pH level of 5.5-7. First, the soil should be well-plowed and necessary nutrients like nitrogen, phosphorus, and potassium should be applied. When planting rice seeds, select seeds at a rate of 20-25 kg per hectare. 10-15 days after sowing, it's important to regularly remove weeds to protect the living plants from jungle and other weeds. Pay attention to water management; rice plants need sufficient water to ensure growth. Don't forget to control pests at the right time to ensure plant growth and crop protection. Finally, be alert for the right time to harvest the rice crop.",

    "maize": "Complete guide for farmers wanting to grow maize: Choosing the right climate and soil is crucial for maize cultivation. Deep, fertile soil with good drainage is considered suitable for maize. A soil pH level of 5.8-7.0 is good. First, the soil should be well-plowed and necessary nutrients like nitrogen, phosphorus, and potassium should be applied. When planting maize seeds, select seeds at a rate of 25-30 kg per hectare. 7-10 days after sowing, it's important to regularly remove weeds to protect the living plants from jungle and other weeds. Pay attention to water management; maize plants need sufficient water every 25-30 days for growth and development. Don't forget to control pests at the right time to ensure plant growth and crop protection. Finally, be alert for the right time to harvest the maize crop.",

    "chickpea": "Complete guide for farmers wanting to grow chickpeas: Choosing the right climate and soil is crucial for chickpea cultivation. Strong, fertile soil with good drainage is necessary for chickpeas, and a soil pH level of 6.0-7.5 is considered suitable. First, the soil should be well-plowed and necessary nutrients like nitrogen, phosphorus, and potassium should be applied. When planting chickpea seeds, select seeds at a rate of 50-60 kg per hectare. 5-7 days after sowing, it's important to regularly remove weeds to protect the living plants from jungle and other weeds. Provide the chickpea plants with the necessary amount of water, especially during flower and fruit development. Don't forget to control pests at the right time to ensure plant growth and crop protection. Finally, be alert for the right time to harvest the chickpea crop.",

    "kidneybeans": "Complete guide for farmers wanting to grow kidney beans: Choosing the right climate and soil is crucial for kidney bean cultivation. Strong, fertile soil with good drainage is necessary for kidney beans, and a soil pH level of 6.0-7.0 is considered suitable. First, the soil should be well-plowed and necessary nutrients like nitrogen, phosphorus, and potassium should be applied. When planting kidney bean seeds, select seeds at a rate of 30-40 kg per hectare. 7-10 days after sowing, it's important to regularly remove weeds to protect the living plants from jungle and other weeds. Provide the kidney bean plants with sufficient water, especially during flower and fruit development. Don't forget to control pests at the right time to ensure plant growth and crop protection. Finally, be alert for the right time to harvest the kidney bean crop.",

    "pigeonpeas": "Complete Guide for Farmers Wishing to Grow Pigeon Peas: Selecting the appropriate climate and soil is crucial for pigeon pea farming. Pigeon peas thrive in fertile soil with good drainage, and the ideal soil pH range is between 6.0 and 7.5. First, the soil should be well plowed, and necessary nutrients such as nitrogen, phosphorus, and potassium should be applied. For sowing, select seeds at a rate of 15-20 kilograms per hectare. Around 10-15 days after sowing, it's important to regularly remove weeds to protect the growing plants from competition. Ensure the plants have sufficient water, especially during the flowering and pod development stages. Don’t forget to implement pest control measures at the right time to ensure healthy plant growth and crop protection. Finally, stay alert for the right time to harvest the pigeon pea crop.",

    "mothbeans": "Complete guide for farmers wanting to grow moth beans: Choosing the right climate and soil is crucial for moth bean cultivation. Light, fertile soil with good drainage is necessary for moth beans, and a soil pH level of 6.0-7.0 is considered suitable. First, the soil should be well-plowed and necessary nutrients like nitrogen, phosphorus, and potassium should be applied. When planting moth bean seeds, select seeds at a rate of 15-20 kg per hectare. 7-10 days after sowing, it's important to regularly remove weeds to protect the living plants from jungle and other weeds. Provide the moth bean plants with sufficient water, especially during flower and fruit development. Don't forget to control pests at the right time to ensure plant growth and crop protection. Finally, be alert for the right time to harvest the moth bean crop.",

    "mungbean": "Complete guide for farmers wanting to grow mung beans: Choosing the right climate and soil is crucial for mung bean cultivation. Light, fertile soil with good drainage is necessary for mung beans, and a soil pH level of 6.0-7.0 is considered suitable. First, the soil should be well-plowed and necessary nutrients like nitrogen, phosphorus, and potassium should be applied. When planting mung bean seeds, select seeds at a rate of 15-20 kg per hectare. 7-10 days after sowing, it's important to regularly remove weeds to protect the living plants from jungle and other weeds. Provide the mung bean plants with sufficient water, especially during flower and fruit development. Don't forget to control pests at the right time to ensure plant growth and crop protection. Finally, be alert for the right time to harvest the mung bean crop.",

    "blackgram": "Complete guide for farmers wanting to grow black gram: Choosing the right climate and soil is crucial for black gram cultivation. Light, fertile soil with good drainage is necessary for black gram, and a soil pH level of 6.0-7.0 is considered suitable. First, the soil should be well-plowed and necessary nutrients like nitrogen, phosphorus, and potassium should be applied. When planting black gram seeds, select seeds at a rate of 20-25 kg per hectare. 7-10 days after sowing, it's important to regularly remove weeds to protect the living plants from jungle and other weeds. Provide the black gram plants with sufficient water, especially during flower and fruit development. Don't forget to control pests at the right time to ensure plant growth and crop protection. Finally, be alert for the right time to harvest the black gram crop.",

    "lentil": "Complete guide for farmers wanting to grow lentils: Choosing the right climate and soil is crucial for lentil cultivation. Light, fertile soil with good drainage is necessary for lentils, and a soil pH level of 6.0-7.5 is considered suitable. First, the soil should be well-plowed and necessary nutrients like nitrogen, phosphorus, and potassium should be applied. When planting lentil seeds, select seeds at a rate of 25-30 kg per hectare. 7-10 days after sowing, it's important to regularly remove weeds to protect the living plants from jungle and other weeds. Provide the lentil plants with sufficient water, especially during flower and fruit development. Don't forget to control pests at the right time to ensure plant growth and crop protection. Finally, be alert for the right time to harvest the lentil crop.",

    "pomegranate": "Complete guide for farmers wanting to grow pomegranates: Choosing the right climate and soil is crucial for pomegranate cultivation. Light, fertile soil with good drainage is necessary for pomegranates, and a soil pH level of 5.5-7.0 is considered suitable. First, prepare the soil well before planting pomegranate saplings and apply necessary nutrients like nitrogen, phosphorus, and potassium. Plant pomegranate saplings 1-2 meters apart, and provide the plants with proper water, especially during hot seasons. It's important to regularly remove weeds from pomegranate plants and manage fertilizer and water properly for plant growth and health. Pay attention during flower and fruit development, and use pesticides when necessary. Finally, be alert for the right time to harvest the pomegranate crop and store the harvest properly.",

    "banana": "Complete guide for farmers wanting to grow bananas: Choosing the right climate and soil is crucial for banana cultivation. Temperate and warm climates are suitable for bananas, and a soil pH level of 5.5-7.0 is considered suitable. First, the soil should be well-plowed and necessary nutrients like nitrogen, phosphorus, and potassium should be applied. When planting banana saplings, plant each sapling 2-3 meters apart. Provide the banana plants with sufficient water, especially during hot seasons, and it's important to regularly remove weeds and jungle to protect the plants. Pay special attention during flower and fruit development and use pesticides when necessary. Finally, be alert for the right time to harvest the banana crop and store the harvest properly.",

    "mango": "Complete guide for farmers wanting to grow mangoes: Choosing the right climate and soil is crucial for mango cultivation. Warm and temperate climates are suitable for mangoes, and a soil pH level of 6.0-7.5 is considered suitable. First, the soil should be well-plowed and necessary nutrients like nitrogen, phosphorus, and potassium should be applied. When planting mango saplings, plant each sapling 8-10 meters apart. Provide the mango plants with sufficient water, especially during hot seasons, and it's important to regularly protect the plants from weeds and jungle. Pay attention during mango flower and fruit development and use pesticides when necessary. Finally, be alert for the right time to harvest the mango crop and store the harvest properly.",

    "grapes": "Complete guide for farmers wanting to grow grapes: Choosing the right climate and soil is crucial for grape cultivation. Warm, dry soil with good drainage is necessary for grapes, and a soil pH level of 6.0-6.5 is considered suitable. First, prepare the soil well and apply necessary nutrients like nitrogen, phosphorus, and potassium. When planting grape vines, plant each vine 2-3 meters apart. Provide the grape plants with sufficient water, especially during flower and fruit development. It's important to regularly remove weeds and manage proper fertilizer and water for plant growth and health. Pay attention during flower and fruit development, and use pesticides when necessary. Finally, be alert for the right time to harvest the grape crop and store the harvest properly.",

    "watermelon": "Complete guide for farmers wanting to grow watermelons: Choosing the right climate and soil is crucial for watermelon cultivation. Warm and dry climates are suitable for watermelons, and a soil pH level of 6.0-6.8 is considered suitable. First, the soil should be well-plowed and necessary nutrients like nitrogen, phosphorus, and potassium should be applied. When planting watermelon seeds, plant them 1-2 meters apart. Provide the watermelon plants with sufficient water, especially during flower and fruit development. It's important to regularly remove weeds and manage proper fertilizer and water for plant growth and health. Pay attention during flower and fruit development, and use pesticides when necessary. Finally, be alert for the right time to harvest the watermelon crop and store the harvest properly.",

    "muskmelon": "Complete guide for farmers wanting to grow muskmelons: Choosing the right climate and soil is crucial for muskmelon cultivation. Warm and dry climates are suitable for muskmelons, and a soil pH level of 6.0-6.8 is considered suitable. First, the soil should be well-plowed and necessary nutrients like nitrogen, phosphorus, and potassium should be applied. When planting muskmelon seeds, plant them 1-2 meters apart. Provide the muskmelon plants with sufficient water, especially during flower and fruit development. It's important to regularly remove weeds and manage proper fertilizer and water for plant growth and health. Pay attention during flower and fruit development, and use pesticides when necessary. Finally, be alert for the right time to harvest the muskmelon crop and store the harvest properly.",

    "apple": "Complete guide for farmers wanting to grow apples: Choosing the right climate and soil is crucial for apple cultivation. Cold and temperate climates are suitable for apples, and a soil pH level of 6.0-7.0 is considered suitable. First, the soil should be well-plowed and necessary nutrients like nitrogen, phosphorus, and potassium should be applied. When planting apple saplings, plant each sapling 5-7 meters apart. Provide the apple plants with sufficient water, especially during flower and fruit development. It's important to regularly remove weeds and manage proper fertilizer and water for plant growth and health. Pay attention during flower and fruit development, and use pesticides when necessary. Finally, be alert for the right time to harvest the apple crop and store the harvest properly.",

    "orange": "Complete guide for farmers wanting to grow oranges: Choosing the right climate and soil is crucial for orange cultivation. Warm and temperate climates are suitable for oranges, and a soil pH level of 6.0-7.5 is considered suitable. First, the soil should be well-plowed and necessary nutrients like nitrogen, phosphorus, and potassium should be applied. When planting orange saplings, plant each sapling 6-8 meters apart. Provide the orange plants with sufficient water, especially during flower and fruit development. It's important to regularly remove weeds and manage proper fertilizer and water for plant growth and health. Pay attention during flower and fruit development, and use pesticides when necessary. Finally, be alert for the right time to harvest the orange crop and store the harvest properly.",

    "papaya": "Complete guide for farmers wanting to grow papayas: Choosing the right climate and soil is crucial for papaya cultivation. Warm and humid climates are suitable for papayas, and a soil pH level of 6.0-7.0 is considered suitable. First, the soil should be well-plowed and necessary nutrients like nitrogen, phosphorus, and potassium should be applied. When planting papaya saplings, plant each sapling 2-3 meters apart. Provide the papaya plants with sufficient water, especially during hot seasons. It's important to regularly remove weeds and manage proper fertilizer and water for plant growth and health. Pay attention during flower and fruit development, and use pesticides when necessary. Finally, be alert for the right time to harvest the papaya crop and store the harvest properly.",

    "coconut": "Complete guide for farmers wanting to grow coconuts: Choosing the right climate and soil is crucial for coconut cultivation. Warm, humid climates are suitable for coconuts, and a soil pH level between 5.0-8.0 is considered suitable. First, prepare the soil well and apply necessary nutrients like nitrogen, phosphorus, and potassium. When planting coconut saplings, plant each sapling 7-8 meters apart. Provide the coconut plants with sufficient water, especially during hot seasons. It's important to regularly remove weeds and manage proper fertilizer and water for plant growth and health. Pay attention during flower and fruit development, and use pesticides when necessary. Finally, be alert for the right time to harvest the coconut crop and store the harvest properly.",

    "cotton": "Complete guide for farmers wanting to grow cotton: Choosing the right climate and soil is crucial for cotton cultivation. Warm and dry climates are suitable for cotton, and a soil pH level of 6.0-7.5 is considered suitable. First, the soil should be well-plowed and necessary nutrients like nitrogen, phosphorus, and potassium should be applied. When planting cotton seeds, plant each seed 20-25 centimeters apart. Provide the cotton plants with sufficient water, especially during flower and fruit development. It's important to regularly remove weeds and manage proper fertilizer and water for plant growth and health. Pay attention during flower and fruit development, and use pesticides when necessary. Finally, be alert for the right time to harvest the cotton crop and store the harvest properly.",

    "jute": "Complete guide for farmers wanting to grow jute: Choosing the right climate and soil is crucial for jute cultivation. Warm, humid climates are suitable for jute, and a soil pH level of 6.0-7.5 is considered suitable. First, the soil should be well-plowed and necessary nutrients like nitrogen, phosphorus, and potassium should be applied. When planting jute seeds, plant each seed 25-30 centimeters apart. Provide the jute plants with sufficient water, especially during flower and fruit development. It's important to regularly remove weeds and manage proper fertilizer and water for plant growth and health. Pay attention during flower and fruit development, and use pesticides when necessary. Finally, be alert for the right time to harvest the jute crop and store the harvest properly.",

    "coffee": "A complete guide for farmers wanting to cultivate coffee: Selecting the right climate and soil is crucial for coffee farming. A temperate and humid climate, with a temperature range of 15-24°C, is ideal for coffee. The soil's pH level should be between 6.0 and 6.5. First, the soil should be well-tilled, and essential nutrients such as nitrogen, phosphorus, and potassium should be applied. When planting coffee, each plant should be spaced 1-2 meters apart. Ensure adequate water for the coffee plants, especially during the summer. It is important to regularly remove weeds and provide proper fertilizer and water to promote plant growth and health. Pay attention during the flowering and fruiting stages, and use pesticides if necessary. Finally, be vigilant for the right time to harvest the coffee crop, and store the harvested crop properly."    }


def recommend_crop(data):
    """
    Given input data, preprocess it and make a prediction.
    Args:
    - data (dict): Input data containing 'N', 'P', 'temperature', 'humidity', 'ph', 'rainfall'.

    Returns:
    - str: Predicted crop name.
    """
    try:
        # Convert input data into DataFrame
        df = pd.DataFrame([data])
        df = df.astype(float)
        
        # Ensure the columns are in the correct order
        df = df[['N', 'P', 'temperature', 'humidity', 'ph', 'rainfall']]
        
        # Apply transformations (log + scaling)
        df[['N', 'P', 'temperature', 'humidity', 'ph', 'rainfall']] = np.log1p(df[['N', 'P', 'temperature', 'humidity', 'ph', 'rainfall']])
        df[['N', 'P', 'temperature', 'humidity', 'ph', 'rainfall']] = sc.transform(df[['N', 'P', 'temperature', 'humidity', 'ph', 'rainfall']])
        
        # Make prediction
        prediction = model.predict(df)
        
        # Inverse transform the prediction to get the original crop label
        crop_prediction = le.inverse_transform(prediction)

        res = {
            "crop": crop_prediction[0],
            "info": crop_info[crop_prediction[0]],
            "info_en":crop_info_en[crop_prediction[0]]
        }
        
        return res
    except Exception as e:
        print(f"Error in prediction: {e}")
        return None
